### ISSUE TITLE
ModuleNotFoundError: No module named 'tables'

### ISSUE THREAD

**Issue by xaviergonzalez** [UCSD-CCAL/ccal#11]
I am currently having difficulty importing CCAL. When I try to open import ccal in a gene pattern nb, I get the error ModuleNotFoundError: No module named 'tables'

The full error message is below. What should I do?
CCAL version 0.6.25 @ /home/jovyan/ccal/ccal/__init__.py
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-d540ba1c96d9> in <module>
      1 import sys
      2 sys.path.insert(0, '/home/jovyan/')
----> 3 import ccal.ccal as ccal

~/ccal/ccal/__init__.py in <module>
      8 from .nmf_map.nmf_map.access_nmf_map import dump_nmf_map
      9 from .nmf_map.nmf_map.access_nmf_map import load_nmf_map
---> 10 from .variant.variant.VariantHDF5 import VariantHDF5
     11 from .variant.variant.access_maf import split_maf_by_tumor_sample_barcode
     12 from .variant.variant.access_maf import make_maf_from_vcf

~/ccal/ccal/variant/variant/VariantHDF5.py in <module>
      4 from warnings import warn
      5 
----> 6 from tables import (Filters, Float32Col, HDF5ExtError, Int32Col, IsDescription,
      7                     StringCol, open_file)
      8 

ModuleNotFoundError: No module named 'tables'

**Comment by KwatME** [comment]
Try `pip isntall pytables`

**Comment by xaviergonzalez** [comment]
> Try `pip isntall pytables`

pip install pytables

isn't working, I'm getting the following error in my terminal:

Could not find a version that satisfies the requirement pytables (from versions: )
No matching distribution found for pytables

When I do 

"conda install pytables"

the command  goes through but then I still get the original error (ModuleNotFoundError: No module named 'tables') when I attempt to import ccal.

I never had this  problem before - has something  changed on the ccal side?

**Comment by KwatME** [comment]
You may have issue in your environment. Could you try following the instructions [here](https://github.com/KwatME/environment/blob/master/configure_environment.md) (up to configuring vi) to re-create an environment?

**Comment by xaviergonzalez** [comment]
I tried the instructions under

"Install jupyter extension"

at https://github.com/KwatME/environment/blob/master/configure_environment.md

because I am using GenePattern NBs. Here was the output:

jovyan@3a147c448deb:~$ jupyter nbextension install --user https://github.com/drillan/jupyter-black/archive/master.zip &&
> jupyter nbextension enable jupyter-black-master/jupyter-black &&
> jupyter nbextension install --user https://github.com/lambdalisue/jupyter-vim-binding/archive/master.zip &&
> jupyter nbextension enable jupyter-vim-binding-master/vim_binding &&
> jupyter nbextension list
Downloading: https://github.com/drillan/jupyter-black/archive/master.zip -> /tmp/tmp2mdojph2/master.zip
Extracting: /tmp/tmp2mdojph2/master.zip -> /home/jovyan/.local/share/jupyter/nbextensions
Enabling notebook extension jupyter-black-master/jupyter-black...
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/opt/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 898, in start
    self.toggle_nbextension(self.extra_args[0])
  File "/opt/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 888, in toggle_nbextension
    logger=self.log)
  File "/opt/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 413, in enable_nbextension
    logger=logger)
  File "/opt/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 351, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/opt/conda/lib/python3.6/site-packages/notebook/config_manager.py", line 136, in update
    self.set(section_name, data)
  File "/opt/conda/lib/python3.6/site-packages/notebook/config_manager.py", line 123, in set
    f = io.open(filename, 'w', encoding='utf-8')
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.jupyter/nbconfig/notebook.json'

Unfortunately, my problems remains even after doing this.

What would you recommend doing?

**Comment by KwatME** [comment]
You don't have to install the extension. You just need to make it up to `vi` part.

I would try out ccal once more. `pip uninstall ccal` and then `pip install ccal`.  If it still does not work, then I would contact people at gene pattern server because the server might have some restrictions.

Best,

**Comment by edjuaro** [comment]
@xaviergonzalez I recommend that you give
` pip install --user ccal`
a try. The PermissionError tells me that you are trying to modify files which users don't have root/write access to. However, by passing the `--user` flag to pip, it knows to modify only local files. I tried this on a dummy account and worked for me (the installation worked, haven't done any tests).

Let us know if that helps!

Edwin.

**Comment by xaviergonzalez** [comment]
Never mind!

I finally got the code to work by importing some packages and changing my import line from 

import ccal.ccal as ccal

to 

import ccal

Thank you so much for all of your help!!
