### ISSUE TITLE
oncogps testing h matrix using_training_h normalization

### ISSUE THREAD

**Issue by ckmah** [UCSD-CCAL/ccal#3]
Hi, I encountered an issue with specificying 'using-training-h' for the parameter testing_h_normalization for ccal.oncogps.make_oncogps(). I believe you may have already fixed the issue, or have it on your todo list because it's tagged TODO.

https://github.com/KwatME/ccal/blob/master/ccal/computational_cancer_biology/oncogps.py#L720

**Comment by KwatME** [comment]
Fixed in the refactor branch. I will make the refactor branch master early next week. Thanks Clarence.
