### ISSUE TITLE
Update dependencies to note Pandas >= 0.20.3

### ISSUE THREAD

**Issue by liefeld** [UCSD-CCAL/ccal#6]
The make_association panel code requires at least Pandas 0.20.3

**Comment by KwatME** [comment]
Thank you for the report. I will get to this today.

**Comment by KwatME** [comment]
Updated setup.py and released [ccal v0.0.3](https://pypi.python.org/pypi/ccal). Please remove your current ccal using:
```bash
$ pip uninstall ccal
```
and then reinstall it by:
```bash
$ pip install ccal
```

Cheers,
