### ISSUE TITLE
Can't import CCAL

### ISSUE THREAD

**Issue by edjuaro** [UCSD-CCAL/ccal#8]
Here is the error I see:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/edjuaro/GoogleDrive/ccal/ccal/__init__.py", line 1, in <module>
    from .linear_model.linear_model.correlate import correlate
  File "/Users/edjuaro/GoogleDrive/ccal/ccal/linear_model/linear_model/correlate.py", line 4, in <module>
    from sklearn.linear_model import LinearRegression
  File "/Users/edjuaro/miniconda3/lib/python3.6/site-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/Users/edjuaro/miniconda3/lib/python3.6/site-packages/sklearn/base.py", line 10, in <module>
    from scipy import sparse
ImportError: cannot import name 'sparse'
```

I don't know what's going on, but it is not as simple as using `from scipy import sparse as sparse_module`

**Comment by KwatME** [comment]
Perhaps the problematic package was updated and we need to change the way we import it. I will investigate further and let you know when I resolve this.

Thanks for the update.

**Comment by KwatME** [comment]
Fixed. Please check if the bug remains.

**Comment by edjuaro** [comment]
Hey, thanks for looking into this!

I cloned ccal and updated the submodules. Then did a local pip instal ("pip install ." inside the main ccal directory). Then I did "conda install --channel conda-forge rpy2 r-mass" and that got rid of the error, but another one showed up.  

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/edjuaro/GoogleDrive/ccal/ccal/__init__.py", line 63, in <module>
>     from .match.match.make_summary_match_panel import make_summary_match_panel
>   File "/Users/edjuaro/GoogleDrive/ccal/ccal/match/match/make_summary_match_panel.py", line 5, in <module>
>     from .information.information.compute_information_coefficient import \
>   File "/Users/edjuaro/GoogleDrive/ccal/ccal/match/match/information/information/compute_information_coefficient.py", line 1, in <module>
>     import rpy2.robjects as ro
>   File "/Users/edjuaro/miniconda3/envs/ccalenv/lib/python3.5/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
>     import rpy2.rinterface as rinterface
>   File "/Users/edjuaro/miniconda3/envs/ccalenv/lib/python3.5/site-packages/rpy2/rinterface/__init__.py", line 50, in <module>
>     from rpy2.rinterface._rinterface import (baseenv,
> ImportError: dlopen(/Users/edjuaro/miniconda3/envs/ccalenv/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libiconv.2.dylib
>   Referenced from: /Users/edjuaro/miniconda3/envs/ccalenv/lib/python3.5/site-packages/rpy2/rinterface/_rinterface.cpython-35m-darwin.so
>   Reason: Incompatible library version: _rinterface.cpython-35m-darwin.so requires version 9.0.0 or later, but libiconv.2.dylib provides version 8.0.0

This one seems to be related to R. What version of R are you using? Are these issues what spro is meant to address?
